# Generated by Django 4.1.1 on 2022-09-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0003_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
