# Generated by Django 4.1.1 on 2022-09-13 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0004_customer_notes"),
        ("ecommerce", "0004_product"),
    ]

    operations = []
